CREATE TABLE RETIRED_EMPLOYEES 
AS SELECT * FROM EMPLOYEES WHERE 1 = 2;

SELECT 
*
FROM RETIRED_EMPLOYEES;
/


DECLARE 
    R_EMP EMPLOYEES%ROWTYPE;
BEGIN
    SELECT 
        *
    INTO R_EMP
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 104;
    
    INSERT INTO RETIRED_EMPLOYEES VALUES R_EMP;
END;    