
DECLARE
    TYPE T_EDU IS RECORD (
        PRIMARY_SCHOOL VARCHAR2(100),
        HIGH_SCHOOL VARCHAR2(100),
        UNIVERSITY VARCHAR2(100),
        UNI_GRADUATE_DATE DATE
    );
    TYPE T_EMP IS RECORD (
        FIRST_NAME VARCHAR2(50),
        LAST_NAME EMPLOYEES.LAST_NAME%TYPE,
        SALARY EMPLOYEES.SALARY%TYPE NOT NULL DEFAULT 1000,
        HIRE_DATE DATE,
        DEPT_ID EMPLOYEES.DEPARTMENT_ID%TYPE,
        DEPARTMENT DEPARTMENTS%ROWTYPE,
        EDUCATION T_EDU
    );
    R_EMP T_EMP;
BEGIN
    
    SELECT 
        FIRST_NAME,
        LAST_NAME,
        SALARY,
        HIRE_DATE,
        DEPARTMENT_ID
    INTO
        R_EMP.FIRST_NAME,
        R_EMP.LAST_NAME,
        R_EMP.SALARY,
        R_EMP.HIRE_DATE,
        R_EMP.DEPT_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = '146';
    
    SELECT 
        * 
    INTO R_EMP.DEPARTMENT
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = R_EMP.DEPT_ID;
    
    R_EMP.EDUCATION.PRIMARY_SCHOOL := 'PRIMARY_SCHOOL';
    R_EMP.EDUCATION.HIGH_SCHOOL := 'Becerly Hills';
    R_EMP.EDUCATION.UNIVERSITY := 'UNIVERSITY';
    R_EMP.EDUCATION.UNI_GRADUATE_DATE := '2013/01/01';
     ------------------------------------------------------------------
    DBMS_OUTPUT.PUT_LINE(R_EMP.FIRST_NAME || ' ' || R_EMP.LAST_NAME);
    DBMS_OUTPUT.PUT_LINE(R_EMP.SALARY || ' ' || R_EMP.HIRE_DATE);
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE(R_EMP.DEPARTMENT.DEPARTMENT_ID);
    DBMS_OUTPUT.PUT_LINE(R_EMP.DEPARTMENT.DEPARTMENT_NAME);
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE(R_EMP.EDUCATION.PRIMARY_SCHOOL);
    DBMS_OUTPUT.PUT_LINE(R_EMP.EDUCATION.HIGH_SCHOOL);
    DBMS_OUTPUT.PUT_LINE(R_EMP.EDUCATION.UNIVERSITY);
    DBMS_OUTPUT.PUT_LINE(R_EMP.EDUCATION.UNI_GRADUATE_DATE);
    
END;
