-- 결과 레코드의 전체 중 일부만을 보여주기 위해 VIEW 사용
-- 최근에는 잘 사용하지 않음

CREATE VIEW HR.VIEW_DEPT_ID_50
AS 
SELECT
    EMPLOYEE_ID,
    UPPER(LAST_NAME) AS "NAME",
    SALARY * 12 AS "ANN_SAL"
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 50;

--

DESC HR.VIEW_DEPT_ID_50;

--
SELECT 
*
FROM HR.VIEW_DEPT_ID_50;

--
DROP VIEW HR.VIEW_DEPT_ID_50;