CREATE USER sampleuser
IDENTIFIED BY oracle4U
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;


GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE,
      CREATE SEQUENCE, CREATE VIEW, ALTER SESSION
TO sampleuser;

-- HR ¿·±Ë «ÿ¡¶

ALTER USER hr 
IDENTIFIED BY oracle4U 
ACCOUNT UNLOCK;