--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUY_COMPANYS
--------------------------------------------------------

  CREATE TABLE "SAMPLEUSER"."BUY_COMPANYS" 
   (	"BC_ID" VARCHAR2(10 BYTE), 
	"BC_NAME" VARCHAR2(100 BYTE), 
	"BC_ADDRESS" VARCHAR2(600 BYTE), 
	"BC_TEL_NUM" VARCHAR2(12 BYTE), 
	"BC_REG_NUM" CHAR(12 BYTE), 
	"BC_OWNWE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAMPLEUSER.BUY_COMPANYS
SET DEFINE OFF;
Insert into SAMPLEUSER.BUY_COMPANYS (BC_ID,BC_NAME,BC_ADDRESS,BC_TEL_NUM,BC_REG_NUM,BC_OWNWE) values ('M1','서울우유 구로동 총판','구로동24','111-222-3333','123-45-12356','홍길동');
Insert into SAMPLEUSER.BUY_COMPANYS (BC_ID,BC_NAME,BC_ADDRESS,BC_TEL_NUM,BC_REG_NUM,BC_OWNWE) values ('M2','남양유업 구로동 총판','구로동35','222-333-4444','321-54-87643','이순신');
Insert into SAMPLEUSER.BUY_COMPANYS (BC_ID,BC_NAME,BC_ADDRESS,BC_TEL_NUM,BC_REG_NUM,BC_OWNWE) values ('M3','해테제과 구로동 총판','시흥대로133','333-444-4444','123-67-89067','이순신');
Insert into SAMPLEUSER.BUY_COMPANYS (BC_ID,BC_NAME,BC_ADDRESS,BC_TEL_NUM,BC_REG_NUM,BC_OWNWE) values ('M4','말보르 구로동 총판','구로동25','123-456-7890','143-78-12456','슈퍼맨');
Insert into SAMPLEUSER.BUY_COMPANYS (BC_ID,BC_NAME,BC_ADDRESS,BC_TEL_NUM,BC_REG_NUM,BC_OWNWE) values ('M5','동서식품 구로동 총판','구로동12','555-555-5555','555-55-55555','김유신');
Insert into SAMPLEUSER.BUY_COMPANYS (BC_ID,BC_NAME,BC_ADDRESS,BC_TEL_NUM,BC_REG_NUM,BC_OWNWE) values ('M6','동아제약 판매점','구로동13','666-666-6666','666-66-66666','강감찬');
--------------------------------------------------------
--  DDL for Index PK_BUY_COMPANYS_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."PK_BUY_COMPANYS_ID" ON "SAMPLEUSER"."BUY_COMPANYS" ("BC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_BC_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."UK_BC_NAME" ON "SAMPLEUSER"."BUY_COMPANYS" ("BC_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_BC_TEL_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."UK_BC_TEL_NUM" ON "SAMPLEUSER"."BUY_COMPANYS" ("BC_TEL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_BC_REG_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."UK_BC_REG_NUM" ON "SAMPLEUSER"."BUY_COMPANYS" ("BC_REG_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUY_COMPANYS
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."BUY_COMPANYS" ADD CONSTRAINT "PK_BUY_COMPANYS_ID" PRIMARY KEY ("BC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLEUSER"."BUY_COMPANYS" MODIFY ("BC_NAME" CONSTRAINT "NN_BC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAMPLEUSER"."BUY_COMPANYS" MODIFY ("BC_TEL_NUM" CONSTRAINT "NN_BC_TEL_NUM" NOT NULL ENABLE);
  ALTER TABLE "SAMPLEUSER"."BUY_COMPANYS" ADD CONSTRAINT "UK_BC_NAME" UNIQUE ("BC_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLEUSER"."BUY_COMPANYS" ADD CONSTRAINT "UK_BC_TEL_NUM" UNIQUE ("BC_TEL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLEUSER"."BUY_COMPANYS" ADD CONSTRAINT "UK_BC_REG_NUM" UNIQUE ("BC_REG_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLEUSER"."BUY_COMPANYS" MODIFY ("BC_REG_NUM" CONSTRAINT "NN_BC_REG_NUM" NOT NULL ENABLE);
