--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUY
--------------------------------------------------------

  CREATE TABLE "SAMPLEUSER"."BUY" 
   (	"BUY_ID" VARCHAR2(10 BYTE), 
	"BUY_DATETIME" DATE, 
	"BUY_COM_ID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAMPLEUSER.BUY
SET DEFINE OFF;
Insert into SAMPLEUSER.BUY (BUY_ID,BUY_DATETIME,BUY_COM_ID) values ('B1',to_date('2022/02/20','YYYY/MM/DD'),'M1');
Insert into SAMPLEUSER.BUY (BUY_ID,BUY_DATETIME,BUY_COM_ID) values ('B2',to_date('2022/02/20','YYYY/MM/DD'),'M3');
Insert into SAMPLEUSER.BUY (BUY_ID,BUY_DATETIME,BUY_COM_ID) values ('B3',to_date('2022/02/20','YYYY/MM/DD'),'M4');
Insert into SAMPLEUSER.BUY (BUY_ID,BUY_DATETIME,BUY_COM_ID) values ('B4',to_date('2022/02/20','YYYY/MM/DD'),'M5');
Insert into SAMPLEUSER.BUY (BUY_ID,BUY_DATETIME,BUY_COM_ID) values ('B5',to_date('2022/02/21','YYYY/MM/DD'),'M1');
Insert into SAMPLEUSER.BUY (BUY_ID,BUY_DATETIME,BUY_COM_ID) values ('B6',to_date('2022/02/22','YYYY/MM/DD'),'M6');
--------------------------------------------------------
--  DDL for Index PK_PURCHASES
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."PK_PURCHASES" ON "SAMPLEUSER"."BUY" ("BUY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUY
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."BUY" ADD CONSTRAINT "PK_BUYS_BUY_ID" PRIMARY KEY ("BUY_ID")
  USING INDEX (CREATE UNIQUE INDEX "SAMPLEUSER"."PK_PURCHASES" ON "SAMPLEUSER"."BUY" ("BUY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "SAMPLEUSER"."BUY" MODIFY ("BUY_DATETIME" CONSTRAINT "NN_BUY_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAMPLEUSER"."BUY" MODIFY ("BUY_COM_ID" CONSTRAINT "NN_BUY_COM_ID" NOT NULL ENABLE);
