--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUY_DETAIL
--------------------------------------------------------

  CREATE TABLE "SAMPLEUSER"."BUY_DETAIL" 
   (	"BUY_ID" VARCHAR2(10 BYTE), 
	"BUY_PROD_ID" VARCHAR2(10 BYTE), 
	"BUY_PROD_QTY" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAMPLEUSER.BUY_DETAIL
SET DEFINE OFF;
Insert into SAMPLEUSER.BUY_DETAIL (BUY_ID,BUY_PROD_ID,BUY_PROD_QTY) values ('B1','A1',10);
Insert into SAMPLEUSER.BUY_DETAIL (BUY_ID,BUY_PROD_ID,BUY_PROD_QTY) values ('B1','A5',10);
Insert into SAMPLEUSER.BUY_DETAIL (BUY_ID,BUY_PROD_ID,BUY_PROD_QTY) values ('B3','A7',10);
Insert into SAMPLEUSER.BUY_DETAIL (BUY_ID,BUY_PROD_ID,BUY_PROD_QTY) values ('B2','A2',5);
Insert into SAMPLEUSER.BUY_DETAIL (BUY_ID,BUY_PROD_ID,BUY_PROD_QTY) values ('B4','A8',5);
Insert into SAMPLEUSER.BUY_DETAIL (BUY_ID,BUY_PROD_ID,BUY_PROD_QTY) values ('B5','A1',10);
Insert into SAMPLEUSER.BUY_DETAIL (BUY_ID,BUY_PROD_ID,BUY_PROD_QTY) values ('B6','A3',10);
--------------------------------------------------------
--  DDL for Index PK_PURCHASES_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."PK_PURCHASES_DETAIL" ON "SAMPLEUSER"."BUY_DETAIL" ("BUY_ID", "BUY_PROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUY_DETAIL
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."BUY_DETAIL" ADD CONSTRAINT "PK_PURCHASES_DETAIL" PRIMARY KEY ("BUY_ID", "BUY_PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLEUSER"."BUY_DETAIL" MODIFY ("BUY_PROD_QTY" CONSTRAINT "NN_BUY_PROD_QTY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BUY_DETAIL
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."BUY_DETAIL" ADD CONSTRAINT "FK_BUY_ID" FOREIGN KEY ("BUY_ID")
	  REFERENCES "SAMPLEUSER"."BUY" ("BUY_ID") ENABLE;
  ALTER TABLE "SAMPLEUSER"."BUY_DETAIL" ADD CONSTRAINT "FK_BUY_PROD_ID" FOREIGN KEY ("BUY_PROD_ID")
	  REFERENCES "SAMPLEUSER"."PRODUCTS" ("PROD_ID") ENABLE;
