--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SAMPLEUSER"."PRODUCTS" 
   (	"PROD_ID" VARCHAR2(10 BYTE), 
	"PROD_NAME" VARCHAR2(100 BYTE), 
	"MANUFACTURER_NAME" VARCHAR2(100 BYTE), 
	"SELL_UNIT_PRICE" NUMBER(8,0), 
	"BUY_UNIT_PRICE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAMPLEUSER.PRODUCTS
SET DEFINE OFF;
Insert into SAMPLEUSER.PRODUCTS (PROD_ID,PROD_NAME,MANUFACTURER_NAME,SELL_UNIT_PRICE,BUY_UNIT_PRICE) values ('A1','흰우유','서울우유',2000,1000);
Insert into SAMPLEUSER.PRODUCTS (PROD_ID,PROD_NAME,MANUFACTURER_NAME,SELL_UNIT_PRICE,BUY_UNIT_PRICE) values ('A2','짱구2','해태제과',1000,1000);
Insert into SAMPLEUSER.PRODUCTS (PROD_ID,PROD_NAME,MANUFACTURER_NAME,SELL_UNIT_PRICE,BUY_UNIT_PRICE) values ('A3','소화제','동아제약',2400,1000);
Insert into SAMPLEUSER.PRODUCTS (PROD_ID,PROD_NAME,MANUFACTURER_NAME,SELL_UNIT_PRICE,BUY_UNIT_PRICE) values ('A4','흰우유','남양유업',2000,1000);
Insert into SAMPLEUSER.PRODUCTS (PROD_ID,PROD_NAME,MANUFACTURER_NAME,SELL_UNIT_PRICE,BUY_UNIT_PRICE) values ('A5','초코우유','서울우유',2000,1000);
Insert into SAMPLEUSER.PRODUCTS (PROD_ID,PROD_NAME,MANUFACTURER_NAME,SELL_UNIT_PRICE,BUY_UNIT_PRICE) values ('A7','말보르 라이트','말보르',4500,4300);
Insert into SAMPLEUSER.PRODUCTS (PROD_ID,PROD_NAME,MANUFACTURER_NAME,SELL_UNIT_PRICE,BUY_UNIT_PRICE) values ('A8','밀크커피캔','동서식품',1200,1000);
--------------------------------------------------------
--  DDL for Index PK_PRODUCTS_PROD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."PK_PRODUCTS_PROD_ID" ON "SAMPLEUSER"."PRODUCTS" ("PROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."PRODUCTS" MODIFY ("PROD_NAME" CONSTRAINT "NN_PRODUCTS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAMPLEUSER"."PRODUCTS" MODIFY ("MANUFACTURER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAMPLEUSER"."PRODUCTS" MODIFY ("SELL_UNIT_PRICE" CONSTRAINT "NN_SELL_UP" NOT NULL ENABLE);
  ALTER TABLE "SAMPLEUSER"."PRODUCTS" MODIFY ("BUY_UNIT_PRICE" CONSTRAINT "NN_BUY_UP" NOT NULL ENABLE);
  ALTER TABLE "SAMPLEUSER"."PRODUCTS" ADD CONSTRAINT "PK_PRODUCTS_PROD_ID" PRIMARY KEY ("PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
