--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALES_DETAIL
--------------------------------------------------------

  CREATE TABLE "SAMPLEUSER"."SALES_DETAIL" 
   (	"SALES_ID" VARCHAR2(10 BYTE), 
	"SALES_PROD_ID" VARCHAR2(10 BYTE), 
	"SALES_PROD_QTY" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAMPLEUSER.SALES_DETAIL
SET DEFINE OFF;
Insert into SAMPLEUSER.SALES_DETAIL (SALES_ID,SALES_PROD_ID,SALES_PROD_QTY) values ('S1','A1',3);
Insert into SAMPLEUSER.SALES_DETAIL (SALES_ID,SALES_PROD_ID,SALES_PROD_QTY) values ('S1','A2',2);
Insert into SAMPLEUSER.SALES_DETAIL (SALES_ID,SALES_PROD_ID,SALES_PROD_QTY) values ('S2','A7',1);
Insert into SAMPLEUSER.SALES_DETAIL (SALES_ID,SALES_PROD_ID,SALES_PROD_QTY) values ('S2','A8',1);
Insert into SAMPLEUSER.SALES_DETAIL (SALES_ID,SALES_PROD_ID,SALES_PROD_QTY) values ('S2','A1',1);
--------------------------------------------------------
--  DDL for Index PK_SALES_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."PK_SALES_DETAIL" ON "SAMPLEUSER"."SALES_DETAIL" ("SALES_ID", "SALES_PROD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SALES_DETAIL
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."SALES_DETAIL" ADD CONSTRAINT "PK_SALES_DETAIL" PRIMARY KEY ("SALES_ID", "SALES_PROD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLEUSER"."SALES_DETAIL" MODIFY ("SALES_PROD_QTY" CONSTRAINT "NN_SALE_PROD_QTY" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SALES_DETAIL
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."SALES_DETAIL" ADD CONSTRAINT "FK_SALE_PROD_ID" FOREIGN KEY ("SALES_PROD_ID")
	  REFERENCES "SAMPLEUSER"."PRODUCTS" ("PROD_ID") ENABLE;
  ALTER TABLE "SAMPLEUSER"."SALES_DETAIL" ADD CONSTRAINT "FK_SALE_ID" FOREIGN KEY ("SALES_ID")
	  REFERENCES "SAMPLEUSER"."SALES" ("SALES_ID") ENABLE;
