--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "SAMPLEUSER"."SALES" 
   (	"SALES_ID" VARCHAR2(10 BYTE), 
	"SALES_DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAMPLEUSER.SALES
SET DEFINE OFF;
Insert into SAMPLEUSER.SALES (SALES_ID,SALES_DATETIME) values ('S1',to_date('2022/02/24','YYYY/MM/DD'));
Insert into SAMPLEUSER.SALES (SALES_ID,SALES_DATETIME) values ('S2',to_date('2022/02/24','YYYY/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_SALES_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLEUSER"."PK_SALES_ID" ON "SAMPLEUSER"."SALES" ("SALES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "SAMPLEUSER"."SALES" ADD CONSTRAINT "PK_SALES_ID" PRIMARY KEY ("SALES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLEUSER"."SALES" MODIFY ("SALES_DATETIME" CONSTRAINT "NN_SALE_DATETIME" NOT NULL ENABLE);
