DECLARE
    V_SALARY_INCREASE NUMBER := 400;

BEGIN
    FOR i IN 207..216 LOOP
        UPDATE EMPLOYEES_COPY
            SET SALARY = SALARY + V_SALARY_INCREASE
        WHERE EMPLOYEE_ID = i;
    END LOOP;
END;
/