-- 병합할 rows 조절
MERGE INTO HR.EMP_APP_TEST T
USING (SELECT * FROM HR.DEPARTMENTS WHERE DEPARTMENT_ID IN (30, 50, 80)) S
ON (T.DEPARTMENT_ID = S.DEPARTMENT_ID)
WHEN MATCHED THEN
UPDATE SET
    T.DEPARTMENT_NAME = NULL
;