SELECT SYSTIMESTAMP,
       SYSTIMESTAMP + TO_DSINTERVAL('00 04:00:00'), -- 'DD HH:MI:SS'
       SYSTIMESTAMP + TO_YMINTERVAL('01-01'), -- 'YY-MM'
       SYSTIMESTAMP + TO_YMINTERVAL(INTERVAL '13' MONTH),
       INTERVAL '13' MONTH, -- +01-01
       INTERVAL '01' MONTH  -- +00-01
FROM DUAL;